# Generated by Django 4.0.6 on 2022-08-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
