# Generated by Django 4.0.6 on 2022-08-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_prestamos_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(blank=True, max_length=255, null=True)),
                ('altura', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'direcciones',
                'managed': False,
            },
        ),
    ]
