# Generated by Django 4.0.6 on 2022-08-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_direcciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('pan', models.CharField(blank=True, max_length=255, null=True)),
                ('cvv', models.CharField(blank=True, max_length=255, null=True)),
                ('numbercard', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tarjetas',
                'managed': False,
            },
        ),
    ]
